### ISSUE TITLE
Issue with 0.94

### ISSUE THREAD

**Issue by gerard33** [mudape/Home-Assistant#1]
I see that you are using `iphonedetect.py` as well. It's working great here, but since 0.94 it's not working for me anymore.

When I check the configuration via the button in the settings of HA, it says it can't find the component, but all files are there and it was working on 0.93.

Is it still working for you?

**Comment by mudape** [comment]
Hi Gerard,
Same for me. I reverted back to 0.93.2 via snapshot and it works again. Haven't looked in to any more, did see notes about changes to device tracker in the release notes. 
Shame, iphonedetect has been working great
    	
    	

    	First, there was nothing. Which exploded. - If anything can go wrong, it will. 
    
  




On Mon, Jun 10, 2019 at 2:58 PM +0200, "Gerard" <notifications@github.com> wrote:












I see that you are using iphonedetect.py as well. It's working great here, but since 0.94 it's not working for me anymore.


When I check the configuration via the button in the settings of HA, it says it can't find the component, but all files are there and it was working on 0.93.


Is it still working for you?

**Comment by gerard33** [comment]
There are some changes in device trackers indeed, but I have some other device trackers which are not changed in the release and still work.

The strange part is that the config checker gives this error:
`Platform not found: device_tracker.iphonedetect`

And the component is there as it was before.

**Comment by mudape** [comment]
Looked at HA's ping device_tracker and made changes. Now it works again :)

**Comment by gerard33** [comment]
Thanks for the fix. I did some digging as well and saw that `DEFAULT_SCAN_INTERVAL` was indeed causing the issue.
